# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ForeverMaze' do
  pod 'Firebase', '>= 2.4.3'  
end

target 'ForeverMazeTests' do
  pod 'Firebase', '>= 2.4.3'
end

target 'ForeverMazeUITests' do
  pod 'Firebase', '>= 2.4.3'
end

